### ISSUE TITLE
Maybe regression bug: Error happens when systemd mode is active.

### ISSUE THREAD

**Issue by yang-ling** [holomorph/systemd-mode#16]
Hi. I think it's a regression bug related to #4 . I open a new issue because #4 is closed.

Now I still get the same error messages while `systemd-mode` is active.

```
Company backend ’t’ could not be initialized:
Symbol’s function definition is void: t
```

My system info:

```
In GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.27, cairo version 1.17.4)
 of 2021-03-27 built on juergen
Windowing system distributor 'The X.Org Foundation', version 11.0.12011000
System Description: Manjaro Linux
```

I checked source code,  and found [this line L410](https://github.com/holomorph/systemd-mode/blob/master/systemd.el#L410)

Should it be changed to `(add-hook 'completion-at-point-functions #'systemd-complete-at-point nil 'local)` ?

I am not familiar with emacs lisp. It's just my guess, because [L409](https://github.com/holomorph/systemd-mode/blob/master/systemd.el#L409) is `(add-hook 'company-backends #'systemd-company-backend nil 'local)`, I think L410 and L409 are very similar, then maybe L410 should also use `'local` as the last parameter of `add-hook` function.

**Comment by yang-ling** [comment]
This error is gone when I change [L409](https://github.com/holomorph/systemd-mode/blob/master/systemd.el#L409) to 

  ``` emacs-lisp
  (push #'systemd-company-backend company-backends)
  ```
  
  I am not an lisp expert so I don't know whether the line above is equivalent of [L409](https://github.com/holomorph/systemd-mode/blob/master/systemd.el#L409), but it solves my issue.
  
  I can send a PR if you think this change is OK.

**Comment by dschrempf** [comment]
FYI, I observe the same error when loading systemd mode.

**Comment by notetiene** [comment]
Using `add-hook` to modify `company-backend` is an anti-pattern in Emacs Lisp.  `add-hook` is for modifying hooks variables.  Making it local removes any previously set backends.

Furthermore, `company-backends` should now use `completion-at-point-functions`.  It's a more appropriate way.[^1]

[^1]: https://company-mode.github.io/manual/Backends.html#Code-Completion

**Comment by dschrempf** [comment]
Do you want to create a PR, @notetiene?

On the other hand: Is this repo still maintained? I do not see any activity.

**Comment by notetiene** [comment]
@stardiviner I could be if it never gets merged, I would have wasted
much time. I do use systemd, but occasionally.  I would much prefer if
this mode could be included in GNU Emacs.  People can come and go, but
big projects as such won't be impacted by lack of interest from the
maintainer.

I'm not sure if the maintainer is still active in this project.

**Comment by dschrempf** [comment]
In my opinion, any situation is better than the current one.

**Comment by holomorph** [comment]
Since it seems like modifying `company-backends' is something a major mode shouldn't be doing, I just nixed the line in 87426071. Keeping the company backend around since it's a TINY quality of life improvement.
