### ISSUE TITLE
support for temporary edit files

### ISSUE THREAD

**Issue by Lompik** [holomorph/systemd-mode#2]
would you mind adding automatic mode switching for systemd's `edit` (usually with `--full`) command. This command creates a temporary file of the form :

    .#offlineimap.service71e9b5a2a790ace9

So basically I would need this:

    (add-to-list 'auto-mode-alist '("\\.#.*\\.service[0-9a-f]*\\'" . systemd-mode))

up to you if you want for mount, timers etc.

Regards

**Comment by holomorph** [comment]
Yeah, I'll look into implementing this

**Comment by holomorph** [comment]
Let me know if  070e15e works for you

**Comment by Lompik** [comment]
see comment in 
https://github.com/holomorph/systemd-mode/commit/070e15e4c083c43c716a223168a27497d5bfdef9 

How about this ?

    (rx (or (and  (or alphanumeric "@") "."
                    (or "automount" "busname" "mount" "service" "slice"
                        "socket" "swap" "target" "timer" "link" "netdev" "network")
                    (?? (= 16 (char hex-digit))) string-end)
                  (and  (? ".#") "override.conf" (? (= 16 (char hex-digit))) string-end)))

I tested this against those cases should return t:

    (string-match systemd-autoload-regexp ".#pulseaudio.service3082e57c830764de")
    (string-match systemd-autoload-regexp ".#override.confe4473d09e1b64fa4")
    (string-match systemd-autoload-regexp "override.conf")
    (string-match systemd-autoload-regexp "pulseaudio.service")
    (string-match systemd-autoload-regexp "pulseaudio@.service")
    (string-match systemd-autoload-regexp "dev-dm\x2d4.service")

and against `.service` should return nil. Let me know if you can thing of other corner case.

**Comment by holomorph** [comment]
Ahh thanks.

I'm not sure just "override.conf" should match. For me, `systemctl edit` always opens a file named `.#override.confXXXXXXXXXXXXXXXX` (or `.#foobar.unitXXX...` with `--full`) which follows from where `tempfn_random` is used in systemd. Is there a command that gives you just `override.conf` ?

Perusing `systemd.unit(5)` a little more carefully I found that `(or alphanumeric "@")` should probably be extended a little bit into `(or alphanumeric (any "-_.@"))`. The handling of a period seems to be a little special, but this regex should be satisfactory

**Comment by Lompik** [comment]
you're right ! ok just saw your edit. so yeah, a user could just create a new file under `unit.d/override.conf` in the sysd folder.  Also matching the `.d/` makes more sense. I just tested with `"\\.d/override.conf\\'"` makes more sense.But it is quite general, lots of `.d` folders in linux. Probably best to leave it in the user config in the documentation but it's up to you. 

to be honest i have never used this override file before looking at the regexps. I thing I might start though ! 

`(or alphanumeric (any "-_.@")) is definately more general. But then I looked at `systemctl list-unit-files --all` but did not see any non alphanumeric before `.`.

Thanks a lot for your feedback!

**Comment by holomorph** [comment]
> I just tested with "\\.d/override.conf\\'" makes more sense.But it is quite general, lots of .d folders in linux.

Yeah, requiring `/systemd/` earlier in the regexp would be more prudent.

> But then I looked at `systemctl list-unit-files --all` but did not see any non alphanumeric before `.`.

I guess `-.slice` is an example

**Comment by holomorph** [comment]
a434645 hopefully grabs all these cases. Writing tests is on the TODO ;)

**Comment by Lompik** [comment]
the tests looks great ! Closing.

Thanks !
