### ISSUE TITLE
Error loading autoloads

### ISSUE THREAD

**Issue by drot** [holomorph/systemd-mode#3]
On `GNU Emacs 25.0.93.1` upon `package-install`:

> For information about GNU Emacs and the GNU system, type C-h C-a.
> Importing package-keyring.gpg...done
> Contacting host: melpa.org:443 [2 times]
> Contacting host: elpa.gnu.org:80
> Package refresh done [2 times]
> Saving file /home/drot/.emacs.d/init.el...
> Wrote /home/drot/.emacs.d/init.el [2 times]
> Saving file /home/drot/.emacs.d/init.el...
> Wrote /home/drot/.emacs.d/init.el [2 times]
> Contacting host: melpa.org:443
> Making version-control local to systemd-autoloads.el while let-bound!
> Generating autoloads for systemd.el...done
> Wrote /home/drot/.emacs.d/elpa/systemd-20160430.1915/systemd-autoloads.el
> Error loading autoloads: (void-variable systemd-autoload-regexp)
> Checking /home/drot/.emacs.d/elpa/systemd-20160430.1915... [3 times]
> Compiling /home/drot/.emacs.d/elpa/systemd-20160430.1915/systemd.el...done
> Wrote /home/drot/.emacs.d/elpa/systemd-20160430.1915/systemd.elc
> Checking /home/drot/.emacs.d/elpa/systemd-20160430.1915...
> Done (Total of 1 file compiled, 2 skipped)
> Error loading autoloads: (void-variable systemd-autoload-regexp)
> You can run the command ‘package-install’ with M-x p-ins RET
> Error loading autoloads: (void-variable systemd-autoload-regexp)

**Comment by holomorph** [comment]
damn it.

**Comment by holomorph** [comment]
I guess autoloading those variables is bearable. b004b37 should fix it

**Comment by drot** [comment]
Yep, fixed.
