### ISSUE TITLE
Emacs 25.1.1: /home/user/unit-directives.txt file not found

### ISSUE THREAD

**Issue by shackra** [holomorph/systemd-mode#5]
For some reason something in the source code of this packages breaks Emacs 25.1.1 initialization because this error:
```
Eager macro-expansion failure: (file-error "Opening input file" "No such file or directory" "/home/jorge/unit-directives.txt")
progn: Opening input file: No such file or directory, /home/jorge/unit-directives.txt
```

This is my setup for systemd:

`(use-package systemd)`

**Comment by holomorph** [comment]
Yeah, it was a problem just using relative file name there. Does 16be183 fix it?

**Comment by shackra** [comment]
Yup, it is fixed now!

El martes 27 de septiembre del 2016 a las 1608 horas, holomorph escribió:

> Yeah, it was a problem just using relative file name there. Does 16be183 fix it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by drot** [comment]
This happens again on `GNU Emacs 26.0.90`

`Error (bytecomp): Opening input file: No such file or directory, /home/drot/.emacs.d/unit-directives.txt`
