### ISSUE TITLE
Support for nspawn files

### ISSUE THREAD

**Issue by danlamanna** [holomorph/systemd-mode#6]
`systemd-nspawn` files are a bit different from service files, see [systemd.nspawn(5)](https://www.freedesktop.org/software/systemd/man/systemd.nspawn.html).

I might add this support if I get the time, just tracking this for posterity.

**Comment by holomorph** [comment]
Yeah, not too different.  I'll poke at it.  Thanks

**Comment by holomorph** [comment]
Added in a simple way in bd94a2cb9

**Comment by danlamanna** [comment]
Thanks!
